/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * todo-app API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import { customInstance } from "./mutator/custom-instance";

export const hello = () => {
  return customInstance<string>({ url: `/hello`, method: "GET" });
};

export type HelloResult = NonNullable<Awaited<ReturnType<typeof hello>>>;
